version: '3.8'

services:
  lisa-dev:
    build:
      context: .
      target: runtime
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=file:./data/dev.db
      - JWT_SECRET=dev_jwt_secret_not_for_production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
      - lisa-dev-data:/app/data
      - lisa-dev-logs:/app/logs
    command: yarn dev:full
    restart: unless-stopped

  # Optional: Redis for caching in development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - lisa-redis-data:/data
    restart: unless-stopped

volumes:
  lisa-dev-data:
    driver: local
  lisa-dev-logs:
    driver: local
  lisa-redis-data:
    driver: local